### ISSUE TITLE
missing documentation wifi connector

### ISSUE THREAD

**Issue by wiensmit** [Xinyuan-LilyGO/T-CAN485#10]
i can't find this anywhere in the documentation, what type of mhf connector fits this board for the wifi antenna.

**Comment by Rojasoterom** [comment]
> i can't find this anywhere in the documentation, what type of mhf connector fits this board for the wifi antenna.

Do you find it? I try but i can't

**Comment by HBK1** [comment]
External wifi antenna can not be used.
Se https://github.com/Xinyuan-LilyGO/T-CAN485/issues/8#issuecomment-1288286752
