### ISSUE TITLE
Expected usage of the bus GND pins?

### ISSUE THREAD

**Issue by bobemoe** [Xinyuan-LilyGO/T-CAN485#14]
The middle pins of the CAN and RS485 bus connectors are labelled AGND and DGND respectively on the schematic and are not connected directly to GND. It appears they connect to GND through a RC filter of some sort and are also connected to the transient voltage suppression components respectively for each bus. 

What is the expected use of this pin. I cant work out if: 

1. Is this pin REQUIRED to be connected to external ground for the voltage protection components to work properly or could it be left unconnected?
2. Is this is a suitable GND point to connect the shield of the bus cables to. I understand the shield should be connected directly to ground and only at one end of the bus. This would be a very convenient location but given that its not directly connected to GND and I cant find any documentation on this pin, I'm unsure if this is a correct use.

![Screenshot_2023-10-25_09-01-25](https://github.com/Xinyuan-LilyGO/T-CAN485/assets/2304970/b3697ec7-f08b-4276-8dee-0f198b71e1da)
https://github.com/Xinyuan-LilyGO/T-CAN485/blob/main/doc/schematic.pdf

**Comment by bobemoe** [comment]
Another possibility here would be, when connecting to an OBD port which has 2 ground pins, signal and chassis:
The signal ground would connect to the middle GND pin along with the CAN hi/low lines, and the chassis ground would connect to the power GND along with the supply voltage line?
I guess then the shield would connect to `chassis ground`.

Really if one of the designers of this board, or someone experienced in this, could shed some light on the intention of these middle GND pins that would be really helpful. Thanks.

**Comment by Llgok** [comment]
> Another possibility here would be, when connecting to an OBD port which has 2 ground pins, signal and chassis: The signal ground would connect to the middle GND pin along with the CAN hi/low lines, and the chassis ground would connect to the power GND along with the supply voltage line? I guess then the shield would connect to chassis ground.
> 
> Really if one of the designers of this board, or someone experienced in this, could shed some light on the intention of these middle GND pins that would be really helpful. Thanks.

AGND is used for the anti-static shielded ground interface of the CAN bus. DGND is used for the anti-static shielded ground interface of the RS485. The function of the two GNDs is to prevent static electricity and protect the circuit board.
@bobemoe
