### ISSUE TITLE
Request: Docs/silkscreen for power connection noting GND/-ve is on the board edge

### ISSUE THREAD

**Issue by Bwooce** [Xinyuan-LilyGO/T-CAN485#17]
There's not a lot of visible guidance on the T-CAN485 board for the power connection, and so I assumed you'd made it idiot proof and put it through a bridge rectifier. Yes I know, "[always read the data sheet](https://github.com/Xinyuan-LilyGO/T-CAN485/blob/main/doc/schematic.pdf)"...

It survived a reverse-polarity event due to your other good design decisions but the board silkscreen writing is obscured once the components are placed e.g. I can't read them on the delivered board, although now I *know* it says GND I can kinda read it and not OOO. So can you please:
1. Either silkscreen the bottom with the power pin polarity, or move the words out into the square in front of the connector?
2. Update your graphics showing the pins and connections to show where +ve/-ve are on these power connectors.

It would also probably be enlightening for some buyers to know these are all plugs and sockets, I thought they were weird screw connectors until I got it and looked closely. I like it, it just wasn't obvious.

**Comment by lewisxhe** [comment]
Hi,

Thank you for your feedback, I have reported it to LilyGo
