### ISSUE TITLE
how to send data from lilygo esp32 by can protocol to another lilygo esp32 by can protocol and read data on serial monitors

### ISSUE THREAD

**Issue by Abdelrahmanars91** [Xinyuan-LilyGO/T-CAN485#22]
hello im use LILYGO esp32 can but when include library not done . this massage  Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: library not valid

**Comment by Llgok** [comment]
> hello im use LILYGO esp32 can but when include library not done . this massage Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: library not valid

If you are using the CAN bus, switch to the arduino_esp32_v3.0.1 branch and refer to [CAN](https://github.com/Xinyuan-LilyGO/T-CAN485/blob/arduino_esp32_v3.0.1/examples/CAN/CAN.ino) example.

@Abdelrahmanars91
