### ISSUE TITLE
Compile error with Arduno IDE T-CAN485

### ISSUE THREAD

**Issue by alcomys** [Xinyuan-LilyGO/T-CAN485#25]
Hello, i want to compile the software into the Lilygo with Arduino but i got this error. 

Documents\Arduino\libraries\FastLED-3.7.0\src\fastspi.h:157:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  157 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

Thanks

**Comment by Llgok** [comment]
@alcomys 
This error belongs to the FastLED-3.7.0 library and has no impact on the project compilation; it can be ignored.
