### ISSUE TITLE
Arduino IDE set up

### ISSUE THREAD

**Issue by antoineTK** [Xinyuan-LilyGO/T-CAN485#3]
Hi team!

I wanted to make sure I was doing the right things setting the Arduino IDE

1- As described in readme file: add https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

2- Restart IDE

3- In board manager look up esp32 and download latest version of esp32 by Espressif Systems

4- When building and uploading choose "ESP32 Arduino --> ESP32-Dev Module"

**Comment by antoineTK** [comment]
If I do it this way and I try building "Freenove_WS2812_Lib_for_ESP32" example sketches I get

In file included from C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\examples\Rainbow\Rainbow.ino:1:
C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src/Freenove_WS2812_Lib_for_ESP32.h:35: warning: "RMT_DEFAULT_CONFIG_TX" redefined
 #define RMT_DEFAULT_CONFIG_TX(gpio, channel_id)      \
 
In file included from C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src/Freenove_WS2812_Lib_for_ESP32.h:18,
                 from C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\examples\Rainbow\Rainbow.ino:1:
C:\Users\Antoine\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2/tools/sdk/esp32/include/driver/include/driver/rmt.h:87: note: this is the location of the previous definition
 #define RMT_DEFAULT_CONFIG_TX(gpio, channel_id)      \
 
In file included from C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src\Freenove_WS2812_Lib_for_ESP32.cpp:12:
C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src\Freenove_WS2812_Lib_for_ESP32.h:35: warning: "RMT_DEFAULT_CONFIG_TX" redefined
 #define RMT_DEFAULT_CONFIG_TX(gpio, channel_id)      \
 
In file included from C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src\Freenove_WS2812_Lib_for_ESP32.h:18,
                 from C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src\Freenove_WS2812_Lib_for_ESP32.cpp:12:
C:\Users\Antoine\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2/tools/sdk/esp32/include/driver/include/driver/rmt.h:87: note: this is the location of the previous definition
 #define RMT_DEFAULT_CONFIG_TX(gpio, channel_id)      \
 
In file included from C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src\Freenove_WS2812_Lib_for_ESP32.cpp:12:
C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src\Freenove_WS2812_Lib_for_ESP32.cpp: In member function 'bool Freenove_ESP32_WS2812::begin()':
C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src\Freenove_WS2812_Lib_for_ESP32.h:53:5: error: no match for 'operator=' (operand types are 'rmt_config_t' and '<brace-enclosed initializer list>')
     }
     ^
C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src\Freenove_WS2812_Lib_for_ESP32.cpp:26:11: note: in expansion of macro 'RMT_DEFAULT_CONFIG_TX'
  config = RMT_DEFAULT_CONFIG_TX(pin, rmt_chn);
           ^~~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src\Freenove_WS2812_Lib_for_ESP32.h:18,
                 from C:\Users\Antoine\Documents\Arduino\libraries\Freenove_WS2812_Lib_for_ESP32\src\Freenove_WS2812_Lib_for_ESP32.cpp:12:
C:\Users\Antoine\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2/tools/sdk/esp32/include/driver/include/driver/rmt.h:81:3: note: candidate: 'rmt_config_t& rmt_config_t::operator=(const rmt_config_t&)'
 } rmt_config_t;
   ^~~~~~~~~~~~
C:\Users\Antoine\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2/tools/sdk/esp32/include/driver/include/driver/rmt.h:81:3: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const rmt_config_t&'
C:\Users\Antoine\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2/tools/sdk/esp32/include/driver/include/driver/rmt.h:81:3: note: candidate: 'rmt_config_t& rmt_config_t::operator=(rmt_config_t&&)'
C:\Users\Antoine\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2/tools/sdk/esp32/include/driver/include/driver/rmt.h:81:3: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'rmt_config_t&&'
exit status 1
Erreur de compilation pour la carte ESP32 Dev Module

**Comment by Roman-Jordan** [comment]
I have no idea at this moment but might be able to poke at it a bit later
today. Gotta get in the line for the homeless shelter early if a want a
place to stay.. so.. we shall see if I get time. Hahaha, your only valuable
in america if you do drugs and have kids. But if you spend your time
learning skills that no one understands.. you deserve to be homeless cause
your less than poop.

**Comment by Roman-Jordan** [comment]
Sorry, just woke up when I had seen this. I will have some time this
evening sometime to poke at this if you want.

**Comment by antoineTK** [comment]
No worries man, I hope your day is going ok!

I was thinking I might use FastLED if I can not figure this out

**Comment by Roman-Jordan** [comment]
Nice. If you got time for a call. I can walk you through it.

**Comment by Roman-Jordan** [comment]
42427257fourTwo Drop me a text when your ready.

**Comment by LilyGO** [comment]
Hello, it can be seen from the log that the WS2812 library is not installed;
1) First compile the flash program from the example to test whether the basic environment is completed.
2) Install all required dependencies
- https://github.com/Freenove/Freenove_WS2812_Lib_for_ESP32
- https://github.com/miwagner/ESP32-Arduino-CAN

**Comment by antoineTK** [comment]
The library was installed but I was getting it from the T-CAN485 repo. Getting it from the repo you linked worked for me, thank you!

In the board selection, can you confirm the default parameters are correct?

![Sans titre](https://user-images.githubusercontent.com/47737047/153146323-43b077ba-b9fc-4260-b1da-13b4255f88f2.png)

**Comment by antoineTK** [comment]
![Sans titre](https://user-images.githubusercontent.com/47737047/153146684-8779bc31-7916-4a61-98da-3c436f9cd698.png)

**Comment by LilyGO** [comment]
There is no problem with your parameter settings.

**Comment by LilyGO** [comment]
FLASH MODE please select DIO

**Comment by antoineTK** [comment]
@LilyGO any ideas?
