### ISSUE TITLE
CAN bus continuously publishes and blocks the programme

### ISSUE THREAD

**Issue by raul-riera-imatia** [Xinyuan-LilyGO/T-CAN485#4]
Hello, good morning!

I have a problem with the CAN bus.
I'm trying the example code found in example/Arduino/CAN
Although the bus should publish at 1000ms intervals, the bus publishes continuously and blocks the program. It never reaches line 89.
Can you help me? Do you know what is wrong?

Thank you very much for your help.

**Comment by LilyGO** [comment]
There may be failures caused by unsuccessful sending. It is recommended that you try connecting the cable before powering on.

**Comment by dalathegreat** [comment]
For anyone still having issues with CAN, I have a repository set up here that uses both CAN and Modbus RTU at the same time on the LilyGo Hardware: https://github.com/dalathegreat/BYD-Battery-Emulator-For-Gen24
