### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by hanusek** [Xinyuan-LilyGO/T-CAN485#5]
Hello. 
I bought LILYGO ESP32 CAN RS485 and take it from the box. I would like to upload to it an example program but I haven't any information. I need a basic tutorial - on how to get started.
I have a problem. Arduino IDE did not recognize the T-CAN485 board (VID: 1A86 PID: 7522).

**Comment by LilyGO** [comment]
1. Install ESP32 board support
2. Connect the USB, select the port
3. Click Upload

**Comment by newdamage1** [comment]
It is more complicated than three steps. The Arduino IDE asks for the board; This board is not listed as an option, esp32 selections error about missing files.

We don't expect a step-by-step for beginners, but your effort at decent documentation would be appreciated by those who spend money on your products.

**Comment by danishzd** [comment]
I am having trouble setting up one that I just bought, My computer does not detect any hardware connection and the board has rapidly switching lights when its plugged in. What am i missing?

**Comment by lewisxhe** [comment]
Is the CH9102 driver installed? You should be able to see a COM device in the Windows Device Manager.

**Comment by danishzd** [comment]
yes made sure to install that on my laptop and the other computer just to try. also tried a different USB cable.

**Comment by lewisxhe** [comment]
ARDUINO IDE only recognizes their own boards. Third-party boards cannot be recognized.

Is it convenient to shoot a video?
, the steps are as follows:
1. Open the computer device manager
2. Insert the USB
3. Check if there is a device in the Port list

**Comment by danishzd** [comment]
I may have receinved a faulty device, it makes no difference when i plug it in or unplug, <img width="1166" height="862" alt="Image" src="https://github.com/user-attachments/assets/748c6197-7292-4275-8e0d-aea851fbd84d" />

**Comment by lewisxhe** [comment]
Device Manager doesn't even respond? Refreshing the device doesn't work?

**Comment by danishzd** [comment]
No, strangely it doesn’t do a thing, not even a sound

**Comment by lewisxhe** [comment]
OK. Then it is damaged. Normally it will recognize the USB and see the USB device in the device manager. If you have just purchased it, please contact the dealer for after-sales service!

**Comment by danishzd** [comment]
I contacted them and they are offering a refund or replacement. They are really slow to response so I just ordered 2 more. Thanks for the help

**Comment by lewisxhe** [comment]
I have received your video and I have already talked to them. They should have arranged the shipment for you.

**Comment by Almendronman** [comment]
> I am having trouble setting up one that I just bought, My computer does not detect any hardware connection and the board has rapidly switching lights when its plugged in. What am i missing?

Same here. My experience is:
1. If I connect the board to a PC's port, nothing happens. Nothing in Linux neither Windows (and yes, I have the drivers)
1.1 In Linux, I can not see any /dev/ttyUSBx neither /dev/ttyACMx
1.2 In Windows, the 'Device Manager' doesn't even blink.
2. If I connect the board to a USB-Smart Charger, nothing happens.
3. If I connect the board to a 'dumb' USB Charger, then the LED starts working and changing colors. The PCB gets really hot, and after a while it stops the LED till I press the Reset or Boot button.
