### ISSUE TITLE
[CAN] Example for Arduino not working

### ISSUE THREAD

**Issue by hanusek** [Xinyuan-LilyGO/T-CAN485#7]
Hello @LilyGO 
I have two TTGO T-CAN485 boards (v1.0 and v1.1).
I'm trying to run the [canbus](https://github.com/Xinyuan-LilyGO/T-CAN485/tree/main/example/Arduino/CAN) example. But I have a problem with it. The Board not sends and receive any can bus frames. I have only `TIME -> CAN send done` in the serial-log.

1.
I found weird things in the schematic and [code](https://github.com/Xinyuan-LilyGO/T-CAN485/blob/07886ab0acd5bdf81f059a37994451682eaa761b/example/Arduino/CAN/config.h#L7). 
**CAN_TX in the schematic == GPIO27
CAN_RX in the schematic == GPIO26**
but in **config.h**:
```
#define CAN_TX_PIN 26
#define CAN_RX_PIN 27
```
It is a bug?

2. I connect my board to the USB port (power + data).  
Did the board require a power supply to work (5 VDC)?
Because in example code we have it:
```
pinMode(PIN_5V_EN, OUTPUT);
digitalWrite(PIN_5V_EN, HIGH);
```

Please help.

**Comment by LilyGO** [comment]
Try using this example.

`https://github.com/Xinyuan-LilyGO/T-CAN485/tree/main/example/PlatfromIO/CAN`
The thing to pay attention to is whether the chip is a V3 version. Q&A in the readme suggests that there is a register that needs to be modified. The modified place is 
`https://github.com/Xinyuan-LilyGO/T-CAN485/blob/07886ab0acd5bdf81f059a37994451682eaa761b/example/PlatfromIO/CAN/lib/ESP32-Arduino-CAN/src/CAN.c#L229`
