### ISSUE TITLE
Error in config.h from can.ino example

### ISSUE THREAD

**Issue by MENIER** [Xinyuan-LilyGO/T-CAN485#9]
Hello, 
It seems to have an error in your example :(https://github.com/Xinyuan-LilyGO/T-CAN485/tree/main/example/Arduino/CAN) in config.h:
```
#define CAN_TX_PIN 26
#define CAN_RX_PIN 27
```
and in CAN.ino
```
CAN_cfg.tx_pin_id = GPIO_NUM_27;
CAN_cfg.rx_pin_id = GPIO_NUM_26;
```

**Comment by Llgok** [comment]
> Hello, It seems to have an error in your example :(https://github.com/Xinyuan-LilyGO/T-CAN485/tree/main/example/Arduino/CAN) in config.h:
> 
> ```
> #define CAN_TX_PIN 26
> #define CAN_RX_PIN 27
> ```
> 
> and in CAN.ino
> 
> ```
> CAN_cfg.tx_pin_id = GPIO_NUM_27;
> CAN_cfg.rx_pin_id = GPIO_NUM_26;
> ```

Please use the latest version branch Arduino_ESP32_v3.0.1 as the main reference.
